drop database if exists tradebook;
create database tradebook;

use tradebook;

CREATE TABLE USUARIO (
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(30) NOT NULL,
  SOBRENOME VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(60) NOT NULL,
  SENHA VARCHAR(60) NOT NULL,
  TELEFONE VARCHAR(15) NOT NULL,
  IMAGEM VARCHAR(180),
  PRIMARY KEY(ID)
);

CREATE TABLE LIVRO (
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(60) NOT NULL,
  AUTOR VARCHAR(30) NOT NULL,
  IDIOMA VARCHAR(30) NOT NULL,
  DESCRICAO LONGTEXT,
  PAGINA INT,
  IMAGEM VARCHAR(180),
  USUARIO_ID INT NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY (USUARIO_ID) references USUARIO (ID)
);

CREATE TABLE COMENTARIO ( 
  ID INT NOT NULL AUTO_INCREMENT,
  LIVRO_ID INT NOT NULL,
  USUARIO_ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (USUARIO_ID) references USUARIO (ID),
  FOREIGN KEY (LIVRO_ID) references LIVRO (ID)
);

CREATE TABLE TROCA (
  ID INT NOT NULL AUTO_INCREMENT,
  MEU_LIVRO INT NOT NULL,
  INTERESSE_LIVRO INT NOT NULL,
  STATUS enum('true', 'false','pendente') DEFAULT 'pendente',

  PRIMARY KEY (ID),
  FOREIGN KEY (MEU_LIVRO) references LIVRO (ID),
  FOREIGN KEY (INTERESSE_LIVRO) references LIVRO (ID)
);

CREATE TABLE AVALIACAO (
  ID INT NOT NULL AUTO_INCREMENT,
  VOTOS INT NOT NULL,
  PONTOS INT NOT NULL,
  ID_LIVRO INT NOT NULL,
  ID_USUARIO INT NOT NULL,

  PRIMARY KEY(ID),
  FOREIGN KEY(ID_LIVRO) references LIVRO(ID),
  FOREIGN KEY(ID_USUARIO) references USUARIO(ID)
);