drop database if exists tradebook;
create database tradebook;

use tradebook;

CREATE TABLE USUARIO (
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(60) NOT NULL,
  SENHA VARCHAR(60) NOT NULL,
  TELEFONE VARCHAR(15) NOT NULL,
  IMAGEM VARCHAR(180),
  PRIMARY KEY(ID)  
);

CREATE TABLE LIVRO (
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(60) NOT NULL,
  AUTOR VARCHAR(30) NOT NULL,
  IDIOMA VARCHAR(30) NOT NULL,
  DESCRICAO LONGTEXT,
  PAGINA INT,
  IMAGEM VARCHAR(180),
  USUARIO_ID INT NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY (USUARIO_ID) references USUARIO (ID)
);

<<<<<<< HEAD
CREATE TABLE COMENTARIO (
  ID INT NOT NULL AUTO_INCREMENT,
  LIVRO_ID INT NOT NULL,
  USUARIO_ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (USUARIO_ID) references USUARIO (ID),
  FOREIGN KEY (LIVRO_ID) references LIVRO (ID)
);
=======
>>>>>>> master
