CREATE DATABASE IF NOT EXISTS tradebook
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE TB_USUARIO (
  US_ID INT NOT NULL AUTO_INCREMENT,
  US_NOME VARCHAR(30) NOT NULL,
  US_EMAIL VARCHAR(60) NOT NULL,
  US_SENHA VARCHAR(60) NOT NULL,
  US_TELEFONE VARCHAR(15) NOT NULL,
  PRIMARY KEY(US_ID)  
) ENGINE = innodb;

CREATE TABLE TB_LIVRO (
  LV_ID INT NOT NULL AUTO_INCREMENT,
  LV_NOME VARCHAR(60) NOT NULL,
  LV_AUTOR VARCHAR(30) NOT NULL,
  LV_IDIOMA VARCHAR(30) NOT NULL,
  LV_DESCRICAO LONGTEXT,
  PRIMARY KEY(LV_ID)
) ENGINE = innodb;